[project]
name = "cartography"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.5",
    "pandas>=2.3.2",
    "polars>=1.33.1",
    "toolz>=1.0.0",
]
